# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.ROOT_DIR}}"
    silent: true
  oapigen:
    dir: "{{.ROOT_DIR}}/server"
    cmds:
      - go tool oapi-codegen -config ".\oapi-config.yaml" "..\api\openapi.yaml"
