# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.ROOT_DIR}}"
    silent: true
  server-oapigen:
    dir: "{{.ROOT_DIR}}/server"
    cmds:
      - go tool oapi-codegen -config ".\oapi-config.yaml" "..\api\openapi.yaml"
  server:
    dir: "{{.ROOT_DIR}}/server"
    cmds:
      - go run ".\cmd\main.go"
  web:
    dir: "{{.ROOT_DIR}}/web"
    cmds:
      - pnpm i && pnpm dev
  web-oapigen:
    dir: "{{.ROOT_DIR}}/web"
    cmds:
      - pnpm i && pnpm openapi-ts
