// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, formDataBodySerializer } from './client';
import type { PostAuthLoginData, PostAuthLoginResponses, PostDataImportLocalData, PostDataImportLocalResponses, PostDataImportUploadData, PostDataImportUploadResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Login
 */
export const postAuthLogin = <ThrowOnError extends boolean = false>(options?: Options<PostAuthLoginData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostAuthLoginResponses, unknown, ThrowOnError>({
        url: '/auth/login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Import Local File
 */
export const postDataImportLocal = <ThrowOnError extends boolean = false>(options?: Options<PostDataImportLocalData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostDataImportLocalResponses, unknown, ThrowOnError>({
        url: '/data/import/local',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Import Upload File
 */
export const postDataImportUpload = <ThrowOnError extends boolean = false>(options?: Options<PostDataImportUploadData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostDataImportUploadResponses, unknown, ThrowOnError>({
        ...formDataBodySerializer,
        url: '/data/import/upload',
        ...options,
        headers: {
            'Content-Type': null,
            ...options?.headers
        }
    });
};