/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Chat: typeof import('./src/components/Chat.vue')['default']
    ChatItem: typeof import('./src/components/chat/ChatItem.vue')['default']
    ChatList: typeof import('./src/components/chat/ChatList.vue')['default']
    ChatToolbar: typeof import('./src/components/chat/ChatToolbar.vue')['default']
    Chip: typeof import('primevue/chip')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('./src/components/chat/Message.vue')['default']
    MessageItem: typeof import('./src/components/chat/MessageItem.vue')['default']
    MessageList: typeof import('./src/components/message/MessageList.vue')['default']
    MessageNode: typeof import('./src/components/message/MessageNode.vue')['default']
    Panel: typeof import('primevue/panel')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextItem: typeof import('./src/components/message/TextItem.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    VirtualScroller: typeof import('primevue/virtualscroller')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
